/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 phone.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/phone.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[1.797, -0.842, -215.255]} rotation={[0, -0.285, 0]}>
          <group position={[-127.797, -549.158, 290.881]} rotation={[0.454, 0, 0]}>
            <group position={[126.483, 492.97, -254.241]} rotation={[-0.742, 0, 0]} scale={0.65}>
              <group position={[0, 0, -1.945]}>
                <mesh geometry={nodes.Boolean_2.geometry} material={nodes.Boolean_2.material} position={[0.357, 358.929, 17.26]} rotation={[0.323, 0, 0]} scale={1.538} />
                <mesh geometry={nodes.Place_your_image_here_2.geometry} material={nodes.Place_your_image_here_2.material} position={[0, 0.5, 17.531]} />
                <mesh geometry={nodes.Front.geometry} material={nodes.Front.material} position={[0, 0, 18.074]} rotation={[-Math.PI, 0, 0]} scale={1.429} />
                <mesh geometry={nodes.Body.geometry} material={nodes.Body.material} position={[0, 0, 1.945]} scale={1.429} />
              </group>
            </group>
            <mesh geometry={nodes.hand.geometry} material={nodes.hand.material} position={[-181.592, 8.78, -12.299]} rotation={[-0.355, 0, -0.661]} scale={3.36} />
          </group>
        </group>
        <PerspectiveCamera makeDefault={false} far={100000} near={70} fov={45} position={[-457.478, 86.908, 999.314]} rotation={[-0.031, -0.021, -0.001]} />
        <directionalLight intensity={0.7} decay={2} rotation={[0, 0.884, 0]} />
        <PerspectiveCamera makeDefault={false} far={100000} near={5} fov={45} position={[-840.512, 73.034, 2109.627]} rotation={[-0.035, -0.379, -0.013]} />
      </group>
    </group>
  )
}
function PhoneMod(){
  return(
    <>
    <Model/>
    </>
  )
}
export default PhoneMod
// useGLTF.preload('/phone.gltf')
